[2024-09-24T05:58:24.798+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-24T05:58:24.821+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_data_transformation.fetch_data manual__2024-09-24T05:58:16.385568+00:00 [queued]>
[2024-09-24T05:58:24.835+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_data_transformation.fetch_data manual__2024-09-24T05:58:16.385568+00:00 [queued]>
[2024-09-24T05:58:24.836+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-24T05:58:24.870+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-09-24 05:58:16.385568+00:00
[2024-09-24T05:58:24.889+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=123) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-24T05:58:24.892+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mysql_data_transformation', 'fetch_data', 'manual__2024-09-24T05:58:16.385568+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/mysql_transform.py', '--cfg-path', '/tmp/tmpp8m2d6de']
[2024-09-24T05:58:24.894+0000] {standard_task_runner.py:72} INFO - Started process 125 to run task
[2024-09-24T05:58:24.895+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask fetch_data
[2024-09-24T05:58:24.984+0000] {task_command.py:467} INFO - Running <TaskInstance: mysql_data_transformation.fetch_data manual__2024-09-24T05:58:16.385568+00:00 [running]> on host a3cfeaba825d
[2024-09-24T05:58:25.119+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_data_transformation' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T05:58:16.385568+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-24T05:58:16.385568+00:00'
[2024-09-24T05:58:25.121+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-24T05:58:25.122+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-24T05:58:25.124+0000] {logging_mixin.py:190} INFO - Current task name:fetch_data state:running start_date:2024-09-24 05:58:24.822332+00:00
[2024-09-24T05:58:25.126+0000] {logging_mixin.py:190} INFO - Dag name:mysql_data_transformation and current dag run status:running
[2024-09-24T05:58:25.127+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-24T05:58:25.144+0000] {base.py:84} INFO - Retrieving connection 'mysql'
[2024-09-24T05:58:25.320+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mysql_transform.py", line 25, in fetch_data_from_mysql
    df = mysql_hook.get_pandas_df(sql)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 282, in get_pandas_df
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1045, "Access denied for user 'root'@'LP048' (using password: YES)")
[2024-09-24T05:58:25.348+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-24T05:58:25.349+0000] {logging_mixin.py:190} INFO - Task start:2024-09-24 05:58:24.822332+00:00 end:2024-09-24 05:58:25.348189+00:00 duration:0.525857
[2024-09-24T05:58:25.350+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_data> dag:<DAG: mysql_data_transformation> dagrun:<DagRun mysql_data_transformation @ 2024-09-24 05:58:16.385568+00:00: manual__2024-09-24T05:58:16.385568+00:00, state:running, queued_at: 2024-09-24 05:58:16.454515+00:00. externally triggered: True>
[2024-09-24T05:58:25.351+0000] {logging_mixin.py:190} INFO - Failure caused by (1045, "Access denied for user 'root'@'LP048' (using password: YES)")
[2024-09-24T05:58:25.352+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=mysql_data_transformation, task_id=fetch_data, run_id=manual__2024-09-24T05:58:16.385568+00:00, execution_date=20240924T055816, start_date=20240924T055824, end_date=20240924T055825
[2024-09-24T05:58:25.375+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-24T05:58:25.376+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task fetch_data ((1045, "Access denied for user 'root'@'LP048' (using password: YES)"); 125)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mysql_transform.py", line 25, in fetch_data_from_mysql
    df = mysql_hook.get_pandas_df(sql)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 282, in get_pandas_df
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1045, "Access denied for user 'root'@'LP048' (using password: YES)")
[2024-09-24T05:58:25.434+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-24T05:58:25.457+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-24T05:58:25.465+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
