[2024-09-25T06:49:13.522+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-25T06:49:13.548+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_data_transformation.load_data manual__2024-09-25T06:43:54.754633+00:00 [queued]>
[2024-09-25T06:49:13.563+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_data_transformation.load_data manual__2024-09-25T06:43:54.754633+00:00 [queued]>
[2024-09-25T06:49:13.566+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-25T06:49:13.593+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_data> on 2024-09-25 06:43:54.754633+00:00
[2024-09-25T06:49:13.609+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=366) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T06:49:13.613+0000] {standard_task_runner.py:72} INFO - Started process 368 to run task
[2024-09-25T06:49:13.612+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mysql_data_transformation', 'load_data', 'manual__2024-09-25T06:43:54.754633+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/mysql_transform.py', '--cfg-path', '/tmp/tmpq3joc9kk']
[2024-09-25T06:49:13.615+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask load_data
[2024-09-25T06:49:13.697+0000] {task_command.py:467} INFO - Running <TaskInstance: mysql_data_transformation.load_data manual__2024-09-25T06:43:54.754633+00:00 [running]> on host 8d2dc09437ab
[2024-09-25T06:49:13.861+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_data_transformation' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T06:43:54.754633+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T06:43:54.754633+00:00'
[2024-09-25T06:49:13.864+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-25T06:49:13.865+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-25T06:49:13.867+0000] {logging_mixin.py:190} INFO - Current task name:load_data state:running start_date:2024-09-25 06:49:13.549357+00:00
[2024-09-25T06:49:13.869+0000] {logging_mixin.py:190} INFO - Dag name:mysql_data_transformation and current dag run status:running
[2024-09-25T06:49:13.870+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-25T06:49:13.889+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mysql_transform.py", line 58, in load_data_to_postgres
    insert_data= {{ti.xcom_pull(task_ids='fetch_data_from_api')}}
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'set'
[2024-09-25T06:49:13.918+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-25T06:49:13.919+0000] {logging_mixin.py:190} INFO - Task start:2024-09-25 06:49:13.549357+00:00 end:2024-09-25 06:49:13.917568+00:00 duration:0.368211
[2024-09-25T06:49:13.921+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_data> dag:<DAG: mysql_data_transformation> dagrun:<DagRun mysql_data_transformation @ 2024-09-25 06:43:54.754633+00:00: manual__2024-09-25T06:43:54.754633+00:00, state:running, queued_at: 2024-09-25 06:43:54.789161+00:00. externally triggered: True>
[2024-09-25T06:49:13.922+0000] {logging_mixin.py:190} INFO - Failure caused by unhashable type: 'set'
[2024-09-25T06:49:13.923+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=mysql_data_transformation, task_id=load_data, run_id=manual__2024-09-25T06:43:54.754633+00:00, execution_date=20240925T064354, start_date=20240925T064913, end_date=20240925T064913
[2024-09-25T06:49:13.948+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-25T06:49:13.950+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 49 for task load_data (unhashable type: 'set'; 368)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/mysql_transform.py", line 58, in load_data_to_postgres
    insert_data= {{ti.xcom_pull(task_ids='fetch_data_from_api')}}
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'set'
[2024-09-25T06:49:13.994+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-25T06:49:14.025+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T06:49:14.031+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
