[2024-10-14T06:31:34.234+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T06:31:34.374+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PIPELINE.EXTRACT scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-14T06:31:34.400+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PIPELINE.EXTRACT scheduled__2024-10-13T00:00:00+00:00 [queued]>
[2024-10-14T06:31:34.402+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-14T06:31:34.449+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): EXTRACT> on 2024-10-13 00:00:00+00:00
[2024-10-14T06:31:34.514+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=107) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T06:31:34.528+0000] {standard_task_runner.py:72} INFO - Started process 119 to run task
[2024-10-14T06:31:34.547+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'PIPELINE', 'EXTRACT', 'scheduled__2024-10-13T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpdbpq_036']
[2024-10-14T06:31:34.551+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask EXTRACT
[2024-10-14T06:31:35.099+0000] {task_command.py:467} INFO - Running <TaskInstance: PIPELINE.EXTRACT scheduled__2024-10-13T00:00:00+00:00 [running]> on host a9d59758bb55
[2024-10-14T06:31:35.289+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PIPELINE' AIRFLOW_CTX_TASK_ID='EXTRACT' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-13T00:00:00+00:00'
[2024-10-14T06:31:35.295+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-14T06:31:35.298+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-14T06:31:35.301+0000] {logging_mixin.py:190} INFO - Current task name:EXTRACT state:running start_date:2024-10-14 06:31:34.376030+00:00
[2024-10-14T06:31:35.303+0000] {logging_mixin.py:190} INFO - Dag name:PIPELINE and current dag run status:running
[2024-10-14T06:31:35.305+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T06:31:35.313+0000] {logging_mixin.py:190} INFO - co2_emi_api
[2024-10-14T06:31:40.470+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline_dag.py", line 98, in EXTRACT
    df = schema_energy_generation(df)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline_dag.py", line 18, in schema_energy_generation
    df = df[['period','fueltype','respondent','value']].rename(columns={'value': 'generation_MWh'})
         ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6179, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['fueltype', 'respondent', 'value'] not in index"
[2024-10-14T06:31:40.536+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-14T06:31:40.537+0000] {logging_mixin.py:190} INFO - Task start:2024-10-14 06:31:34.376030+00:00 end:2024-10-14 06:31:40.534808+00:00 duration:6.158778
[2024-10-14T06:31:40.539+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): EXTRACT> dag:<DAG: PIPELINE> dagrun:<DagRun PIPELINE @ 2024-10-13 00:00:00+00:00: scheduled__2024-10-13T00:00:00+00:00, state:running, queued_at: 2024-10-14 06:31:17.618892+00:00. externally triggered: False>
[2024-10-14T06:31:40.540+0000] {logging_mixin.py:190} INFO - Failure caused by "['fueltype', 'respondent', 'value'] not in index"
[2024-10-14T06:31:40.542+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=PIPELINE, task_id=EXTRACT, run_id=scheduled__2024-10-13T00:00:00+00:00, execution_date=20241013T000000, start_date=20241014T063134, end_date=20241014T063140
[2024-10-14T06:31:40.580+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T06:31:40.582+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task EXTRACT ("['fueltype', 'respondent', 'value'] not in index"; 119)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline_dag.py", line 98, in EXTRACT
    df = schema_energy_generation(df)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline_dag.py", line 18, in schema_energy_generation
    df = df[['period','fueltype','respondent','value']].rename(columns={'value': 'generation_MWh'})
         ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6179, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['fueltype', 'respondent', 'value'] not in index"
[2024-10-14T06:31:40.648+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-14T06:31:40.711+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T06:31:40.724+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
